### ISSUE TITLE
Unable to change fill of single series bar chart

### ISSUE THREAD

**Issue by nross83** [vega/vega-themes#1]
I'm trying to create a custom theme and I'm unable to style any single series marks (multi-series is working great).  The examples also seem to suffer from the same problem.

![screen shot 2017-08-09 at 3 15 11 pm](https://user-images.githubusercontent.com/247567/29144316-bd76d5ca-7d15-11e7-927f-3566735ea141.png)

No matter what I try I can't seem to stop it from being 'steelblue'.  I'm doing the same approach as what's documented here: https://github.com/vega/vega-themes/blob/master/src/theme-quartz.js#L7-L15.

**Comment by jheer** [comment]
Thanks for posting the issue! This repo had fallen out of sync with the most up-to-date Vega 3. I've updated the themes and examples in this repo and they are working now -- if you pull the latest from master the problems should resolve.

The main change to know about is that Vega config files no longer place mark-type config under a `mark` property. Each mark type (`rect`, `line`, etc.) can now be used as a top-level property.
