### ISSUE TITLE
Make test/index.html the webpage? 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-themes#10]

**Comment by iFlameing** [comment]
@kanitw I would like to work on this issue. we can make test/index.html webpage simply moving this to gh-pages branch and webpage is hosted at https://gihtub.com/vega/vega-themes.

**Comment by domoritz** [comment]
I would love a PR towards this. The most important thing is to make this as seamless as possible for developers. I'd love to do this automatically with travis releases, for example. See how I set up the deployment for Falcon, Vega-Embed, Vega-Tooltip and https://github.com/vega/vega-transform-omnisci-core.

**Comment by iFlameing** [comment]
@domoritz there is already travis.yml which push the new build to npm packages. Do I need to change this configuration or simply I have to file a pr as you set up the [vega-tooltip](https://github.com/vega/vega-tooltip/tree/gh-pages).


thanks for the reply :)
I gsoc aspirants. And selected vega-theme as my project.

**Comment by iFlameing** [comment]
@domoritz I saw your code how you hosted vega-tooltip and Falcon. Just one doubt, when I am running
test/index.html it does not show any visualization


![screenshot from 2019-02-28 02-25-13](https://user-images.githubusercontent.com/33936987/53522343-2e0aa880-3b00-11e9-8a73-c8cd02090912.png)

I also download the Falcon gh-pages branch and tried to run the index.html it also give me just
`Loading data. Please wait..` . How I can check locally if build works fine or not?

**Comment by domoritz** [comment]
We're building from master and use the gh-pages npm module to deploy. You don't have to try all the repos I sent you but I thought they might be useful resources to see some examples of how we could do this.
