### ISSUE TITLE
Example chart needed to test and debug diverging color schemes

### ISSUE THREAD

**Issue by palewire** [vega/vega-themes#15]
Is there a good example of using the theme's default diverging scheme in the Vega example gallery? If so, let me know and I'll add it here as an example.

**Comment by domoritz** [comment]
I don't think we have a good example, yet.

**Comment by palewire** [comment]
How does Vega-Lite detect that the diverging color scheme is necessary? Negative and positive values in a quantitative scale?

**Comment by domoritz** [comment]
It doesn't right now. Vega-Lite never sees the data and so it cannot choose the color scheme based on it but we could potentially generate code that does it. It would have to be very strict, though, because diverging scales make the most sense when the domain is symmetric around some meaningful null value. So at the end of the day, we should probably only do it for fixed domains (where the user already set it explicitly).

**Comment by palewire** [comment]
So what's the value of defining a diverging color scheme? Can I pull it out of the theme somehow by referencing the theme object?

**Comment by domoritz** [comment]
I was wrong. @kanit noted that we should be using the diverging scale automatically when `domainMid` is set. Also see https://github.com/vega/vega-lite/issues/4323.

**Comment by domoritz** [comment]
https://vega.github.io/editor/#/examples/vega-lite/point_diverging_color is an example that uses a diverging scale automatically.

**Comment by palewire** [comment]
That's true, but if I [subtract the color scheme from that spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJh2HdmOSEx3PGFiJuAd0ZLqYV7th33ZF0wZTAAD1UwVEZbWDBCILBaMQclONCAT0j0JU0wN2RGanx85kQwdDBNRipdJi8weG4HYIR0Wzo1DUhNdDxMHGBIVl0xbC0+9FJ4dD95RRUAX3UISAxdAGtxyEJuTzwu1eQlJuqvcdAIVbCLyAAzRmQxTW2ACW4-AILdNUg8DIS2wAjqwckZ+kYqJBlhpVhlbg8ni9TABZGI6AD6CV0GIA4u1Ur9-oDTCCwcw+jVkNCVldIE0WhdYXTEc9tgB1QrFPAYzwYsTsWCHK6rYnU0mgpTgylQ2kiyBtWxMkXyzTcDCecYAbQAjAAGA2RaQAJgArHrIgAWc16gC6zIgi2ZTsdICdQA) it doesn't seem to fall back on a default divergent color scheme from the theme, which is the behavior I think we'd need for a theme's divergent scheme to come into play.

**Comment by domoritz** [comment]
I agree that we should figure out when to use diverging scales. 

Right now we seem to be ignoring all values except the first and the last when the range is a normal quantitative scheme: https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJh2HdmOSEx3PGFiJuAd0ZLqYV7th33ZF0wZTAAD1UwVEZbWDBCILBaMQclONCAT0j0JU0wN2RGanx85kQwdDBNRipdJi8weG4HYIR0Wzo1DUhNdDxMHGBIVl0xbC0+9FJ4dD95RRUAX3UISAxdAGtxyEJuTzwu1eQlJuqvcdAIVbCLyAAzRmQxTW2ACW4-AILdNUg8DIS2wAjqwckZ+kYqJBlhpVhlbg8ni9TABZGI6AD6CV0GIA4u1Ur9-oDTCCwcw+jVkNCVldIE0WhdYXTEc9tgB1QrFPAYzwYsTsWCHK6rYnU0mgpTgylQ2kiyBtWxMkXyzTcDCecYAbQAjAAGA2qACcBtNhoALABWA0AXWZEEWzMdDpAjqAA. 

Note that Vega has a major cleanup of scales coming and so we will revise how Vega-Lite handles scales in the near future. We can put this improvement on the queue. 

cc @kanitw

**Comment by domoritz** [comment]
Closing in favor of https://github.com/vega/vega-lite/issues/4542
