### ISSUE TITLE
Minor grid?

### ISSUE THREAD

**Issue by baptiste** [vega/vega-themes#262]
I'm not sure if it's possible at this level, or if it would require changes in the parent project, but for the ggplot2 theme the most salient difference is the lack of a minor grid (thinner lines half-way). Maybe I've just become too used to it, but I find it a subtle tweak that makes the plot more polished (whether in grey background or white).
<img width="1068" alt="Screen Shot 2021-04-23 at 2 06 55 PM" src="https://user-images.githubusercontent.com/18970/115807673-2ffcf780-a43d-11eb-9359-2b2a3872e0b1.png">

**Comment by domoritz** [comment]
That does look nice. Could you file this as an enhancement request for Vega? [Vega's axes](https://vega.github.io/vega/docs/axes/) do not support minor grids right now.
