### ISSUE TITLE
Dark theme preview should use dark background for the whole page 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-themes#30]

**Comment by domoritz** [comment]
In general, we should use the background color of the theme.

**Comment by syntagmatic** [comment]
Screenshots from the PR #40:

<img width="841" alt="Screen Shot 2019-07-15 at 8 06 44 PM" src="https://user-images.githubusercontent.com/156229/61263145-b8b11480-a73c-11e9-84ab-23ca401a274f.png">
<img width="849" alt="Screen Shot 2019-07-15 at 8 06 33 PM" src="https://user-images.githubusercontent.com/156229/61263146-b8b11480-a73c-11e9-959d-83970175c732.png">
