### ISSUE TITLE
Presentation Theme

### ISSUE THREAD

**Issue by deisi** [vega/vega-themes#35]
All the themes/styles available as of right now change the color.
 
Is there a theme that changes the the size? I'm looking for something like https://matplotlib.org/users/style_sheets.html#defining-your-own-style. This way one can easily create figures for presentations, where axis labels and legends are huge so that people in the back row can read of ticks.

From what I understand in matplotlib this is easily possible by downsizing the figure. Thus fonts become relatively larger. However I have not found a way to to this with altair and I was hoping to find a theme to the rescue.

**Comment by deisi** [comment]
thx a lot

**Comment by domoritz** [comment]
Can we close this issue?
