### ISSUE TITLE
How to style actions dropdown & tooltips?

### ISSUE THREAD

**Issue by theiliad** [vega/vega-themes#580]
Hi,
I'm working on a more official-looking Carbon theme.

I'd need to also be able to style the action bar

![image](https://github.com/vega/vega-themes/assets/14989804/f7e0d5e9-d874-41bc-847b-9a92e02887a2)

and the tooltips

![image](https://github.com/vega/vega-themes/assets/14989804/d9335656-c0e1-4830-bbf6-bf16cc7e0b28)

is there a proposed way to do this right now?

Thank you

**Comment by domoritz** [comment]
The menu comes from Vega-embed and the tooltip from Vega-tooltip. Both of those allow for some styling with custom CSS.

**Comment by theiliad** [comment]
Thanks @domoritz for the info. So thinking in terms of themes, how can we get the Carbon theme to more closely match up with the actual specs? Should I contribute an additional CSS file that you'd import with the theme?

What is your suggested approach?

**Comment by domoritz** [comment]
I don't think tooltips and the menu need to match the themes. But it would be nice to have a light mode and dark mode. A pull request for that (using media queries) would be great.
